import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Load local fonts and set CSS variables
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const popsies = localFont({
  src: "./fonts/Popsies.ttf",
  variable: "--font-popsies", // Unique variable name for Popsies font
  weight: "100 900",
});

// Define metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${popsies.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}